// Manual data for Mexico City - Plans added manually
import { ValentinePlan } from './service';

export const MEXICO_CITY_MANUAL_PLANS: ValentinePlan[] = [
  {
    id: '273924',
    title: 'Malinche: El Musical',
    venue: 'Frontón México Centro de Entretenimiento, Avenida de la República 17',
    price: 'From MX$450',
    priceValue: 450,
    link: 'https://feverup.com/m/273924',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/2ecf151a-be37-11ef-bead-7a191a1aeef5.jpg',
    rank: 1,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '346941',
    title: 'Tim Burton, El Laberinto',
    venue: 'Avenida Constituyentes 500',
    price: 'From MX$280',
    priceValue: 280,
    link: 'https://feverup.com/m/346941',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/018cf09a-1611-11f0-a76f-9a434eb12399.jpg',
    rank: 2,
    categories: ['experiences-and-exhibitions', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '185255',
    title: 'Mystika: Un Viaje Inmersivo Espiritual',
    venue: 'Torre Cuarzo, Avenida Paseo de la Reforma 26',
    price: 'From MX$330',
    priceValue: 330,
    link: 'https://feverup.com/m/185255',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/f1924976-69e8-11ef-a7cf-7a0a6dada98e.jpg',
    rank: 3,
    categories: ['experiences-and-exhibitions', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '468643',
    title: 'Light Cycles: ¡Una experiencia inmersiva nocturna entre luces y sonidos de la naturaleza!',
    venue: 'Jardín Escénico Chapultepec, Av. P.º de la Reforma 111',
    price: 'From MX$250',
    priceValue: 250,
    link: 'https://feverup.com/m/468643',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/d31ee772-d9a1-11f0-8c9f-5e6dda6dca2c.jpeg',
    rank: 4,
    categories: ['experiences-and-exhibitions', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '473349',
    title: 'Candlelight: Especial de San Valentín',
    venue: 'El Cantoral, Puente Xoco s/n-Puerta A',
    price: 'From MX$300',
    priceValue: 300,
    link: 'https://feverup.com/m/473349',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/a1c08570-d73d-11f0-a29d-1e898d3afd0b.jpg',
    rank: 5,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: true,
    eventDates: []
  },
  {
    id: '357089',
    title: 'Cabinas VIP',
    venue: 'Aztlán Feria de Chapultepec, Avenida de los Compositores s/n',
    price: 'From MX$968',
    priceValue: 968,
    link: 'https://feverup.com/m/357089',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/ef390f32-eb17-11f0-83bd-36e988987708.jpeg',
    rank: 6,
    categories: ['food', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '369901',
    title: 'Ballet of Lights: La Bella Durmiente en un espectáculo deslumbrante',
    venue: 'Foro Interlomas, Boulevard Interlomas 41',
    price: 'From MX$290',
    priceValue: 290,
    link: 'https://feverup.com/m/369901',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/ff3ab810-1915-11f0-a1d4-1aafc7b2ca0e.jpg',
    rank: 7,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '335242',
    title: 'The Jazz Room: Un Viaje al Corazón de Nueva Orleans',
    venue: 'Hilton Santa Fe, Antonio Dovali Jaime 70',
    price: 'From MX$290',
    priceValue: 290,
    link: 'https://feverup.com/m/335242',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/d41e2e90-570f-11f0-b2c5-f295a86a2f76.jpg',
    rank: 8,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '542521',
    title: 'Parejas "Experiencia de ensoñación sensorial"',
    venue: 'Sensorama, Zacatecas 155, Roma Norte',
    price: 'MX$1,110',
    priceValue: 1110,
    link: 'https://feverup.com/m/542521',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/2e3b0354-eb66-11f0-b15d-ee5f9faf7227.jpg',
    rank: 9,
    categories: ['workshops-and-activities', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '484628',
    title: 'Experiencia Platino',
    venue: 'WTC México, Montecito 38',
    price: 'MX$2,000',
    priceValue: 2000,
    link: 'https://feverup.com/m/484628',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/7e6a9294-a616-11f0-ba52-6a0c6153bd1c',
    rank: 10,
    categories: ['food', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '131257',
    title: 'Cena maridaje en Alma Café',
    venue: 'Alma Café CDMX, Heriberto Frías 205',
    price: 'From MX$1,670',
    priceValue: 1670,
    link: 'https://feverup.com/m/131257',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/6133f026-ffec-11ed-9df3-9eb735ff1db6.jpg',
    rank: 11,
    categories: ['food', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '120271',
    title: 'Sensoria Gastroexperiencia by NIDO',
    venue: 'NIDO Taller Culinario, Av Sonora 189',
    price: 'MX$3,500',
    priceValue: 3500,
    link: 'https://feverup.com/m/120271',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/9d1fa8ca-4b18-11ed-b610-2a22ba484fc3.jpg',
    rank: 12,
    categories: ['food', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '105595',
    title: 'Visita Narvarte de noche: degustación de tacos, chelas y mezcal',
    venue: 'Cumbres de Maltrata, Narvarte Poniente',
    price: 'MX$2,395',
    priceValue: 2395,
    link: 'https://feverup.com/m/105595',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/d2a85640-3e99-11ec-b525-0ed0321796c8.jpg',
    rank: 13,
    categories: ['food', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '117588',
    title: 'Noche mexicana: Lucha Libre + Tequila + Tacos y Guacamole',
    venue: 'Terraza Casa Pepe, República de Uruguay 89',
    price: 'MX$1,500',
    priceValue: 1500,
    link: 'https://feverup.com/m/117588',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/ed406ea2-6e5b-11f0-8be4-f2cf7dcdad91',
    rank: 14,
    categories: ['food', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '143239',
    title: 'Leyendas El Show',
    venue: 'Stelaris Foro Reforma, Avenida Paseo de la Reforma 80-Piso 25',
    price: 'MX$900',
    priceValue: 900,
    link: 'https://feverup.com/m/143239',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/5e6fad9e-af28-11ee-adf7-daa12a9bdbd2.jpg',
    rank: 15,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '552371',
    title: 'Pablo Marentes "Mi homenaje al Príncipe"',
    venue: 'Stelaris Foro Reforma, Avenida Paseo de la Reforma 80-Piso 25',
    price: 'MX$700',
    priceValue: 700,
    link: 'https://feverup.com/m/552371',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/1e5e6e6c-f156-11f0-8879-86f1310a9f09.jpeg',
    rank: 16,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '470899',
    title: 'Tropical Fuck Storm',
    venue: 'Foro Indie Rocks!, Zacatecas 39',
    price: 'From MX$550',
    priceValue: 550,
    link: 'https://feverup.com/m/470899',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/558b11f4-a9ff-11f0-a1d9-5ee38305a50d',
    rank: 17,
    categories: ['concerts-musicals-theater'],
    city: 'mexico-city',
    isCandlelight: false,
    eventDates: []
  }
];
