// Manual data for München - Plans added manually
import { ValentinePlan } from './service';

export const MUENCHEN_MANUAL_PLANS: ValentinePlan[] = [
  {
    id: '352884',
    title: 'Ballet of Lights: Dornröschen in einer funkelnden Show',
    venue: 'Fat Cat, Kellerstraße 8a',
    price: 'From €22',
    priceValue: 22,
    link: 'https://feverup.com/m/352884',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/4629cac8-eaac-11f0-aab0-6e1baecb4a46.jpg',
    rank: 1,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'munchen',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '455793',
    title: 'Candlelight: Valentinstags-Special',
    venue: 'St Matthäus, Nußbaumstraße 1',
    price: 'From €20',
    priceValue: 20,
    link: 'https://feverup.com/m/455793',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/bf86b91a-cea7-11f0-9f85-d265d7fb50bf.jpg',
    rank: 2,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'munchen',
    isCandlelight: true,
    eventDates: []
  },
  {
    id: '485843',
    title: 'Date Night Scavenger Hunt: Mission München',
    venue: 'Luisenstraße 31',
    price: '€19.99',
    priceValue: 19.99,
    link: 'https://feverup.com/m/485843',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/59ded7ee-a8e3-11f0-9608-ce32d170f432',
    rank: 3,
    categories: ['experiences-and-exhibitions', 'valentines-related-events'],
    city: 'munchen',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '549909',
    title: 'Valentinstag: Paarzeit-Schatzsuche München Altstadt',
    venue: 'Königsplatz',
    price: '€24.99',
    priceValue: 24.99,
    link: 'https://feverup.com/m/549909',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/fb508ad6-ef98-11f0-a1f6-a2010356f60c.jpeg',
    rank: 4,
    categories: ['experiences-and-exhibitions', 'valentines-related-events'],
    city: 'munchen',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '478723',
    title: 'Paarmomente: München für Zwei - Die Schatzsuche',
    venue: 'Luisenstraße 31',
    price: '€19.99',
    priceValue: 19.99,
    link: 'https://feverup.com/m/478723',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/87290562-9fc4-11f0-8bac-56f67cf8abf1',
    rank: 5,
    categories: ['experiences-and-exhibitions', 'valentines-related-events'],
    city: 'munchen',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '106611',
    title: 'Hard Rock Cafe München: Genieße einen köstlichen Burger!',
    venue: 'Hard Rock Cafe Munich, Platzl 1',
    price: 'From €28.15',
    priceValue: 28.15,
    link: 'https://feverup.com/m/106611',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/b330b976-4d3d-11ec-b58e-d2e1489d0ef7',
    rank: 6,
    categories: ['food', 'valentines-related-events'],
    city: 'munchen',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '143689',
    title: 'Pauls kulinarische Tour durch München',
    venue: 'Walking Tours München, Arnulfstraße 2',
    price: 'From €90',
    priceValue: 90,
    link: 'https://feverup.com/m/143689',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/fb7158d2-7caf-11ee-a9bc-b6e3f0044e3d',
    rank: 7,
    categories: ['food', 'valentines-related-events'],
    city: 'munchen',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '107138',
    title: 'Biertour München auf Englisch',
    venue: 'Radius Tours, Dachauer Straße 4',
    price: 'From €70',
    priceValue: 70,
    link: 'https://feverup.com/m/107138',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/42a294da-534c-11ec-89e1-3e0a30ec3d41',
    rank: 8,
    categories: ['food', 'valentines-related-events'],
    city: 'munchen',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '143670',
    title: 'Bayerische Bier- & Schmankerltour durch München',
    venue: 'Beer and Oktoberfest Museum, Sterneckerstraße 2',
    price: 'From €95',
    priceValue: 95,
    link: 'https://feverup.com/m/143670',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/570f205e-7cae-11ee-8ba0-2ee3722b2bb8',
    rank: 9,
    categories: ['food', 'valentines-related-events'],
    city: 'munchen',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '364403',
    title: 'Latte Art Kurs max. 5 Personen',
    venue: 'The Colombian Coffee Bar, Reisingerstraße 3',
    price: 'From €50',
    priceValue: 50,
    link: 'https://feverup.com/m/364403',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/480352b0-30df-11f0-8a58-ceb9c0471e3b.jpg',
    rank: 10,
    categories: ['food', 'valentines-related-events'],
    city: 'munchen',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '107209',
    title: 'Bavarian Beer and Food Evening Tour in Munich',
    venue: 'Dachauer Str. 4',
    price: '€71.95',
    priceValue: 71.95,
    link: 'https://feverup.com/m/107209',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/b12d8f14-5427-11ec-9717-0a67087c25a8.jpg',
    rank: 11,
    categories: ['food', 'valentines-related-events'],
    city: 'munchen',
    isCandlelight: false,
    eventDates: []
  }
];
