// Manual data for Roma - Plans added manually
import { ValentinePlan } from './service';

export const ROMA_MANUAL_PLANS: ValentinePlan[] = [
  {
    id: '473049',
    title: 'Candlelight: Speciale San Valentino',
    venue: 'Boscolo Circo Massimo, Via dei Cerchi, 87',
    price: 'From €20',
    priceValue: 20,
    link: 'https://feverup.com/m/473049',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/d39afaa4-f1ea-11f0-9f3e-424d61552d33.jpg',
    rank: 1,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: true,
    eventDates: []
  },
  {
    id: '349184',
    title: 'The Jazz Room: un viaggio nel cuore di New Orleans',
    venue: 'Largo Venue, Via Biordo Michelotti, 2',
    price: 'From €34',
    priceValue: 34,
    link: 'https://feverup.com/m/349184',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/2d9203c2-5d80-11f0-8283-aabf995c80bd.jpg',
    rank: 2,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '125559',
    title: 'Opera in Roma: Three Tenors - Nessun Dorma',
    venue: 'Chiesa di San Paolo Entro le Mura, Via Nazionale, 16a',
    price: 'From €20',
    priceValue: 20,
    link: 'https://feverup.com/m/125559',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/3930d908-9b38-11ee-acac-c6432f7b24a8.jpg',
    rank: 3,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '126944',
    title: 'Candlelight Ballet: Il Lago dei Cigni e altre opere',
    venue: 'Teatro Ghione, Via delle Fornaci, 37',
    price: 'From €20',
    priceValue: 20,
    link: 'https://feverup.com/m/126944',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/073db61e-2020-11f0-a226-461578d92733.jpg',
    rank: 4,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: true,
    eventDates: []
  },
  {
    id: '112187',
    title: "I Virtuosi dell'Opera di Roma: le più belle arie d'opera",
    venue: 'Chiesa di San Paolo Entro le Mura, Via Nazionale, 16a',
    price: 'From €25',
    priceValue: 25,
    link: 'https://feverup.com/m/112187',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/bebbf988-aa92-11ec-b1bc-96895289f4cf',
    rank: 5,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '122640',
    title: 'Musica lirica con aperitivo sulla Terrazza Borromini',
    venue: "Sant'Agnese in Agone, Via di Santa Maria dell'Anima, 30/A",
    price: '€157.95',
    priceValue: 157.95,
    link: 'https://feverup.com/m/122640',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/e4328f18-7226-11ed-a820-8e4232062a30.jpg',
    rank: 6,
    categories: ['food', 'concerts-musicals-theater', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '147232',
    title: 'Ristorante Alfredo alla Scrofa: Menu con le Fettucine Alfredo originali',
    venue: 'Alfredo at the Scrofa, Via della Scrofa, 104/a',
    price: '€120',
    priceValue: 120,
    link: 'https://feverup.com/m/147232',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/1792a9e2-98cd-11ee-812c-fe9b3ef6d5f6',
    rank: 7,
    categories: ['food', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '146838',
    title: 'Cena gourmet con abbinamento di vini vicino al Pantheon',
    venue: 'Piazza della Minerva',
    price: 'From €169',
    priceValue: 169,
    link: 'https://feverup.com/m/146838',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/fbbdad40-938e-11ee-a4b0-0a46113d35ab',
    rank: 8,
    categories: ['food', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '112195',
    title: 'Lezione di cucina: impara a preparare pizza, pasta e gelato',
    venue: 'InRome Cooking, Corso del Rinascimento, 65',
    price: '€89',
    priceValue: 89,
    link: 'https://feverup.com/m/112195',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/c44a7354-aa95-11ec-a380-723cbfaf8e1e',
    rank: 9,
    categories: ['food', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '147262',
    title: 'Corso di Gelato e Fettuccine a Roma',
    venue: 'Day Trips from Rome, Via Cavour',
    price: '€89',
    priceValue: 89,
    link: 'https://feverup.com/m/147262',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/87911396-98cd-11ee-812c-fe9b3ef6d5f6',
    rank: 10,
    categories: ['food', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '146789',
    title: 'Corso di pasta, ravioli e tiramisù a Roma',
    venue: "PummaRe', Via Andrea Doria, 41m",
    price: '€82',
    priceValue: 82,
    link: 'https://feverup.com/m/146789',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/3c7b2408-938e-11ee-8ad5-12ca22bb0d4a',
    rank: 11,
    categories: ['food', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '146813',
    title: 'Workshop per gli amanti della pasta e del tiramisù: un must a Roma',
    venue: 'Third Party Passes Rome, Via Gaetano Moroni, 16',
    price: 'From €56',
    priceValue: 56,
    link: 'https://feverup.com/m/146813',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/824f0486-938e-11ee-8ad5-12ca22bb0d4a',
    rank: 12,
    categories: ['food', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '147281',
    title: 'Corso di pizzaiolo di 1 ora a Roma',
    venue: 'Day Trips from Rome, Via Cavour',
    price: '€53',
    priceValue: 53,
    link: 'https://feverup.com/m/147281',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/ccb6b782-98cd-11ee-ba4c-862c7d16c4d8',
    rank: 13,
    categories: ['food', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '146870',
    title: 'Quartiere di Trevi sotterraneo: Acquedotto e Domus Visita guidata',
    venue: 'Vicolo del Puttarello, 25',
    price: 'From €38',
    priceValue: 38,
    link: 'https://feverup.com/m/146870',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/ee8bbd86-9390-11ee-ad15-16c6731d47be',
    rank: 14,
    categories: ['experiences-and-exhibitions', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '146815',
    title: 'Gita in Toscana da Roma con Pranzo Incluso',
    venue: 'Cattedrale di Santa Maria Assunta, Piazza Grande, Montepulciano',
    price: 'From €69',
    priceValue: 69,
    link: 'https://feverup.com/m/146815',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/8ae60a5e-938e-11ee-bbbb-4a496e02fdda',
    rank: 15,
    categories: ['experiences-and-exhibitions', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '491251',
    title: 'Trastevere e Campo de Fiori Roma: Tour guidato del cibo',
    venue: 'Tour Gastronomici a Roma, Via Cipro, 4 L',
    price: 'From €68.50',
    priceValue: 68.5,
    link: 'https://feverup.com/m/491251',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/8c0c81da-ad89-11f0-b32c-0ea7bc048e27',
    rank: 16,
    categories: ['food', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '147293',
    title: 'Roma: Cena italiana con vista panoramica',
    venue: 'Piazzale Aurelio',
    price: 'Free',
    priceValue: 0,
    link: 'https://feverup.com/m/147293',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/15dd773e-98ce-11ee-83b7-8e33073f95e8',
    rank: 17,
    categories: ['food', 'valentines-related-events'],
    city: 'roma',
    isCandlelight: false,
    eventDates: []
  }
];
