// Manual data for Toronto - Plans added manually
import { ValentinePlan } from './service';

export const TORONTO_MANUAL_PLANS: ValentinePlan[] = [
  {
    id: '550173',
    title: "Valentine's Tufting Workshop for Two: Create Your Own Rug",
    venue: '4789 Yonge St',
    price: 'From CA$250',
    priceValue: 250,
    link: 'https://feverup.com/m/550173',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/6a9ed754-f001-11f0-adab-767a010463ad.png',
    rank: 1,
    categories: ['workshops-and-activities', 'valentines-related-events'],
    city: 'toronto',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '274809',
    title: 'The Jazz Room: A Journey to the Heart of New Orleans',
    venue: 'Lula Lounge',
    price: 'From CA$29',
    priceValue: 29,
    link: 'https://feverup.com/m/274809',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/1581fec2-5722-11f0-8a32-8616f23b8bdb.jpg',
    rank: 2,
    categories: ['concerts-musicals-theater'],
    city: 'toronto',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '197954',
    title: 'Tufting Workshop',
    venue: 'EmoTuft Tufting Studio | NorthYork',
    price: 'From CA$210',
    priceValue: 210,
    link: 'https://feverup.com/m/197954',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/783006bc-7c9a-11ef-be26-e240eb831424.jpg',
    rank: 3,
    categories: ['workshops-and-activities'],
    city: 'toronto',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '198533',
    title: 'Splatter Painting in Toronto',
    venue: 'Emopaints Splatter Toronto',
    price: 'From CA$50',
    priceValue: 50,
    link: 'https://feverup.com/m/198533',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/525c766a-c3ca-11ef-a3a7-8619e02addd6.jpg',
    rank: 4,
    categories: ['workshops-and-activities'],
    city: 'toronto',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '169273',
    title: 'Romantic Jewel - Private Helicopter Tour for 2',
    venue: 'Toronto Heli Tours',
    price: 'From CA$369',
    priceValue: 369,
    link: 'https://feverup.com/m/169273',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/9b08e37c-f8f4-11ee-b451-02f082039469',
    rank: 5,
    categories: ['valentines-related-events'],
    city: 'toronto',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '271250',
    title: 'Candlelight Valentines: Classical Romance',
    venue: 'Metropolitan Community Church of Toronto',
    price: 'From CA$40',
    priceValue: 40,
    link: 'https://feverup.com/m/271250',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/a4251344-6861-11f0-90b8-ee5a9ea828c9.jpg',
    rank: 6,
    categories: ['concerts-musicals-theater', 'valentines-related-events'],
    city: 'toronto',
    isCandlelight: true,
    eventDates: []
  },
  {
    id: '429287',
    title: 'The Jazz Room: Tribute to The Blues',
    venue: 'Lula Lounge',
    price: 'From CA$29',
    priceValue: 29,
    link: 'https://feverup.com/m/429287',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/13aca0e4-f6c2-11f0-b4c9-9e6a7ec75937.jpg',
    rank: 7,
    categories: ['concerts-musicals-theater'],
    city: 'toronto',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '473328',
    title: 'The Jazz Room: Tribute to Soul',
    venue: 'Lula Lounge',
    price: 'From CA$39',
    priceValue: 39,
    link: 'https://feverup.com/m/473328',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/57e03c6a-6bfa-11f0-97a5-062f645e08fd.jpg',
    rank: 8,
    categories: ['concerts-musicals-theater'],
    city: 'toronto',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '178494',
    title: 'Private Canadian Food Discovery at the St Lawrence Market',
    venue: 'Hockey Hall of Fame, Brookfield Place',
    price: 'From CA$139',
    priceValue: 139,
    link: 'https://feverup.com/m/178494',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/5d728e38-113f-11ef-b8cb-12ea240cf4e7',
    rank: 9,
    categories: ['food', 'valentines-related-events'],
    city: 'toronto',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '135437',
    title: 'Toronto: Local Beer Tour',
    venue: 'Gateway Newstands',
    price: 'CA$89',
    priceValue: 89,
    link: 'https://feverup.com/m/135437',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/28bafca6-1f01-11ee-ad45-362f41e285e9',
    rank: 10,
    categories: ['food'],
    city: 'toronto',
    isCandlelight: false,
    eventDates: []
  },
  {
    id: '166840',
    title: 'Pub Crawl Toronto',
    venue: 'Toronto',
    price: 'CA$59',
    priceValue: 59,
    link: 'https://feverup.com/m/166840',
    imageUrl: 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/c45b3d7e-f37c-11ee-80e3-fea05bb5f581',
    rank: 11,
    categories: ['food'],
    city: 'toronto',
    isCandlelight: false,
    eventDates: []
  }
];
